import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/header/header";
import NewUserContext from "@/components/NewUserContext";

export const metadata: Metadata = {
  title: "Blogs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`overflow-x-hidden m-0 p-0 `} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NewUserContext>
            <Header />
            {children}
          </NewUserContext>

          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
